// Merchant Category Code descriptions (ISO 18245).
//
// Only the codes actually present in merchants.csv are listed — an unknown
// code falls back to showing the bare number rather than nothing.

const MCC_NAMES = {
  4111: 'Commuter Passenger Transport',
  4121: 'Taxicabs & Limousines',
  4131: 'Bus Lines',
  4511: 'Airlines & Air Carriers',
  4722: 'Travel Agencies & Tour Operators',
  4789: 'Transportation Services',
  4814: 'Telecommunication Services',
  4816: 'Computer Network & Information Services',
  4899: 'Cable, Satellite & Pay Television',
  4900: 'Utilities — Electric, Gas, Water, Sanitary',
  5309: 'Duty Free Stores',
  5310: 'Discount Stores',
  5311: 'Department Stores',
  5399: 'Miscellaneous General Merchandise',
  5411: 'Grocery Stores & Supermarkets',
  5422: 'Freezer & Locker Meat Provisioners',
  5441: 'Candy, Nut & Confectionery Stores',
  5451: 'Dairy Products Stores',
  5462: 'Bakeries',
  5499: 'Convenience & Specialty Food Stores',
  5541: 'Service Stations',
  5621: 'Women’s Ready-to-Wear Stores',
  5651: 'Family Clothing Stores',
  5661: 'Shoe Stores',
  5691: 'Men’s & Women’s Clothing Stores',
  5699: 'Miscellaneous Apparel & Accessories',
  5712: 'Furniture & Home Furnishings',
  5732: 'Electronics Stores',
  5812: 'Eating Places & Restaurants',
  5813: 'Bars, Taverns & Nightclubs',
  5814: 'Fast Food Restaurants',
  5815: 'Digital Goods — Media, Books, Movies, Music',
  5817: 'Digital Goods — Applications (Excludes Games)',
  5912: 'Drug Stores & Pharmacies',
  5921: 'Package Stores — Beer, Wine & Liquor',
  5940: 'Bicycle Shops',
  5942: 'Book Stores',
  5943: 'Stationery & Office Supply Stores',
  5944: 'Jewelry & Watch Stores',
  5945: 'Hobby, Toy & Game Shops',
  5946: 'Camera & Photographic Supply Stores',
  5968: 'Direct Marketing — Subscription Merchants',
  5970: 'Artist’s Supply & Craft Shops',
  5977: 'Cosmetic Stores',
  5992: 'Florists',
  5994: 'News Dealers & Newsstands',
  6012: 'Financial Institutions — Merchandise & Services',
  6051: 'Money Orders, Foreign Currency & Crypto',
  6211: 'Security Brokers & Dealers',
  6300: 'Insurance Sales & Premiums',
  6513: 'Real Estate Agents & Managers — Rentals',
  7011: 'Lodging — Hotels, Motels & Resorts',
  7298: 'Health & Beauty Spas',
  7299: 'Miscellaneous Personal Services',
  7333: 'Commercial Photography, Art & Graphics',
  7372: 'Computer Programming & Data Processing',
  7512: 'Automobile Rental Agencies',
  7523: 'Parking Lots, Garages & Meters',
  7832: 'Motion Picture Theaters',
  7991: 'Tourist Attractions & Exhibits',
  7997: 'Membership Clubs & Private Golf Courses',
  7998: 'Aquariums & Seaquariums',
  8211: 'Elementary & Secondary Schools',
  8398: 'Charitable & Social Service Organizations',
  9399: 'Government Services',
  9402: 'Postal Services — Government Only',
};

// "5451" -> "Dairy Products Stores"; '' when the code is absent or unlisted.
export function mccName(mcc) {
  return MCC_NAMES[(mcc || '').trim()] || '';
}
