// Merchant Category Code descriptions (ISO 18245).
//
// Every generic code. The brand-specific airline, car rental and hotel codes
// (3000–3999) are left out; networks report those under their generic code
// (4511, 7512, 7011) too. Names are based on the public-domain list at
// https://github.com/greggles/mcc-codes, shortened and cleaned up. An unknown
// code falls back to showing the bare number rather than nothing.
//
// Keys are strings: several codes start with a zero ("0742").

const MCC_NAMES = {
  '0742': 'Veterinary Services',
  '0763': 'Agricultural Co-operatives',
  '0780': 'Landscaping & Horticultural Services',
  '1520': 'General Contractors — Residential & Commercial',
  '1711': 'Heating, Plumbing & Air Conditioning Contractors',
  '1731': 'Electrical Contractors',
  '1740': 'Masonry, Stonework, Tile, Plastering & Insulation Contractors',
  '1750': 'Carpentry Contractors',
  '1761': 'Roofing, Siding & Sheet Metal Contractors',
  '1771': 'Concrete Work Contractors',
  '1799': 'Special Trade Contractors',
  '2741': 'Miscellaneous Publishing & Printing',
  '2791': 'Typesetting, Plate Making & Related Services',
  '2842': 'Specialty Cleaning, Polishing & Sanitation Preparations',
  '4011': 'Railroads',
  '4111': 'Commuter Passenger Transport',
  '4112': 'Passenger Railways',
  '4119': 'Ambulance Services',
  '4121': 'Taxicabs & Limousines',
  '4131': 'Bus Lines',
  '4214': 'Motor Freight, Moving & Storage, Local Delivery',
  '4215': 'Courier Services — Air or Ground, Freight Forwarders',
  '4225': 'Public Warehousing & Storage',
  '4411': 'Cruise & Steamship Lines',
  '4457': 'Boat Rentals & Leases',
  '4468': 'Marinas, Marine Service & Supplies',
  '4511': 'Airlines & Air Carriers',
  '4582': 'Airports, Airport Terminals, Flying Fields',
  '4722': 'Travel Agencies & Tour Operators',
  '4723': 'Package Tour Operators (Germany)',
  '4784': 'Toll & Bridge Fees',
  '4789': 'Transportation Services',
  '4812': 'Telecommunication Equipment & Telephone Sales',
  '4814': 'Telecommunication Services',
  '4815': 'VisaPhone',
  '4816': 'Computer Network & Information Services',
  '4821': 'Telegraph Services',
  '4829': 'Wire Transfer Money Orders',
  '4899': 'Cable, Satellite & Pay Television',
  '4900': 'Utilities — Electric, Gas, Water, Sanitary',
  '5013': 'Motor Vehicle Supplies & New Parts',
  '5021': 'Office & Commercial Furniture',
  '5039': 'Construction Materials',
  '5044': 'Office, Photographic, Photocopy & Microfilm Equipment',
  '5045': 'Computers, Peripherals & Software',
  '5046': 'Commercial Equipment',
  '5047': 'Medical, Dental, Ophthalmic & Hospital Equipment',
  '5051': 'Metal Service Centers & Offices',
  '5065': 'Electrical Parts & Equipment',
  '5072': 'Hardware Equipment & Supplies',
  '5074': 'Plumbing & Heating Equipment & Supplies',
  '5085': 'Industrial Supplies',
  '5094': 'Precious Stones & Metals, Watches & Jewelry',
  '5099': 'Durable Goods',
  '5111': 'Stationery, Office Supplies & Printing Paper',
  '5122': 'Drugs, Drug Proprietaries & Druggist’s Sundries',
  '5131': 'Piece Goods, Notions & Other Dry Goods',
  '5137': 'Uniforms & Commercial Clothing',
  '5139': 'Commercial Footwear',
  '5169': 'Chemicals & Allied Products',
  '5172': 'Petroleum & Petroleum Products',
  '5192': 'Books, Periodicals & Newspapers',
  '5193': 'Florists’ Supplies, Nursery Stock & Flowers',
  '5198': 'Paints, Varnishes & Supplies',
  '5199': 'Non-Durable Goods',
  '5200': 'Home Supply Warehouse Stores',
  '5211': 'Lumber & Building Materials Stores',
  '5231': 'Glass, Paint & Wallpaper Stores',
  '5251': 'Hardware Stores',
  '5261': 'Nurseries & Garden Supply',
  '5271': 'Mobile Home Dealers',
  '5300': 'Wholesale Clubs',
  '5309': 'Duty Free Stores',
  '5310': 'Discount Stores',
  '5311': 'Department Stores',
  '5331': 'Variety Stores',
  '5399': 'Miscellaneous General Merchandise',
  '5411': 'Grocery Stores & Supermarkets',
  '5422': 'Freezer & Locker Meat Provisioners',
  '5441': 'Candy, Nut & Confectionery Stores',
  '5451': 'Dairy Products Stores',
  '5462': 'Bakeries',
  '5499': 'Convenience & Specialty Food Stores',
  '5511': 'Car & Truck Dealers — New & Used',
  '5521': 'Car & Truck Dealers — Used Only',
  '5531': 'Automobile Supply Stores',
  '5532': 'Automotive Tire Stores',
  '5533': 'Automotive Parts & Accessories Stores',
  '5541': 'Service Stations',
  '5542': 'Automated Fuel Dispensers',
  '5551': 'Boat Dealers',
  '5561': 'Camper, Recreational & Utility Trailer Dealers',
  '5571': 'Motorcycle Dealers',
  '5592': 'Motor Home Dealers',
  '5598': 'Snowmobile Dealers',
  '5599': 'Miscellaneous Auto Dealers',
  '5611': 'Men’s & Boys’ Clothing & Accessories Stores',
  '5621': 'Women’s Ready-to-Wear Stores',
  '5631': 'Women’s Accessory & Specialty Shops',
  '5641': 'Children’s & Infants’ Wear Stores',
  '5651': 'Family Clothing Stores',
  '5655': 'Sports & Riding Apparel Stores',
  '5661': 'Shoe Stores',
  '5681': 'Furriers & Fur Shops',
  '5691': 'Men’s & Women’s Clothing Stores',
  '5697': 'Tailors & Alterations',
  '5698': 'Wig & Toupee Stores',
  '5699': 'Miscellaneous Apparel & Accessories',
  '5712': 'Furniture & Home Furnishings',
  '5713': 'Floor Covering Stores',
  '5714': 'Drapery, Window Covering & Upholstery Stores',
  '5718': 'Fireplace & Accessories Stores',
  '5719': 'Miscellaneous Home Furnishing Specialty Stores',
  '5722': 'Household Appliance Stores',
  '5732': 'Electronics Stores',
  '5733': 'Music Stores — Instruments & Sheet Music',
  '5734': 'Computer Software Stores',
  '5735': 'Record Shops',
  '5811': 'Caterers',
  '5812': 'Eating Places & Restaurants',
  '5813': 'Bars, Taverns & Nightclubs',
  '5814': 'Fast Food Restaurants',
  '5815': 'Digital Goods — Media, Books, Movies, Music',
  '5816': 'Digital Goods — Games',
  '5817': 'Digital Goods — Applications (Excludes Games)',
  '5818': 'Digital Goods — Large Digital Goods Merchant',
  '5832': 'Antique Shops — Sales, Repairs & Restoration',
  '5912': 'Drug Stores & Pharmacies',
  '5921': 'Package Stores — Beer, Wine & Liquor',
  '5931': 'Used Merchandise & Secondhand Stores',
  '5932': 'Antique Shops',
  '5933': 'Pawn Shops',
  '5935': 'Wrecking & Salvage Yards',
  '5937': 'Antique Reproductions',
  '5940': 'Bicycle Shops',
  '5941': 'Sporting Goods Stores',
  '5942': 'Book Stores',
  '5943': 'Stationery & Office Supply Stores',
  '5944': 'Jewelry & Watch Stores',
  '5945': 'Hobby, Toy & Game Shops',
  '5946': 'Camera & Photographic Supply Stores',
  '5947': 'Gift, Card, Novelty & Souvenir Shops',
  '5948': 'Leather Goods Stores',
  '5949': 'Sewing, Needlework, Fabric & Piece Goods Stores',
  '5950': 'Glassware & Crystal Stores',
  '5960': 'Direct Marketing — Insurance Service',
  '5961': 'Mail Order Houses',
  '5962': 'Direct Marketing — Travel Services',
  '5963': 'Door-to-Door Sales',
  '5964': 'Direct Marketing — Catalog Merchant',
  '5965': 'Direct Marketing — Catalog & Retail Merchant',
  '5966': 'Direct Marketing — Outbound Telemarketing Merchant',
  '5967': 'Direct Marketing — Inbound Teleservices Merchant',
  '5968': 'Direct Marketing — Subscription Merchants',
  '5969': 'Direct Marketing — Other',
  '5970': 'Artist’s Supply & Craft Shops',
  '5971': 'Art Dealers & Galleries',
  '5972': 'Stamp & Coin Stores',
  '5973': 'Religious Goods Stores',
  '5975': 'Hearing Aids — Sales, Service & Supplies',
  '5976': 'Orthopedic Goods & Prosthetic Devices',
  '5977': 'Cosmetic Stores',
  '5978': 'Typewriter Stores — Sales, Rental & Service',
  '5983': 'Fuel Dealers — Fuel Oil, Wood, Coal & LPG',
  '5992': 'Florists',
  '5993': 'Cigar Stores & Stands',
  '5994': 'News Dealers & Newsstands',
  '5995': 'Pet Shops, Pet Food & Supplies',
  '5996': 'Swimming Pools — Sales, Service & Supplies',
  '5997': 'Electric Razor Stores — Sales & Service',
  '5998': 'Tent & Awning Shops',
  '5999': 'Miscellaneous & Specialty Retail Stores',
  '6010': 'Financial Institutions — Manual Cash Disbursements',
  '6011': 'Automated Cash Disbursements (ATM)',
  '6012': 'Financial Institutions — Merchandise & Services',
  '6051': 'Money Orders, Foreign Currency & Crypto',
  '6211': 'Security Brokers & Dealers',
  '6300': 'Insurance Sales & Premiums',
  '6381': 'Insurance Premiums',
  '6399': 'Insurance',
  '6513': 'Real Estate Agents & Managers — Rentals',
  '7011': 'Lodging — Hotels, Motels & Resorts',
  '7012': 'Timeshares',
  '7032': 'Sporting & Recreational Camps',
  '7033': 'Campgrounds & Trailer Parks',
  '7210': 'Laundry, Cleaning & Garment Services',
  '7211': 'Laundry — Family & Commercial',
  '7216': 'Dry Cleaners',
  '7217': 'Carpet & Upholstery Cleaning',
  '7221': 'Photographic Studios',
  '7230': 'Barber & Beauty Shops',
  '7251': 'Shoe Repair, Shoe Shine & Hat Cleaning',
  '7261': 'Funeral Services & Crematories',
  '7273': 'Dating & Escort Services',
  '7276': 'Tax Preparation Services',
  '7277': 'Counseling Service — Debt, Marriage, Personal',
  '7278': 'Buying & Shopping Services',
  '7296': 'Clothing Rental — Costumes, Formal Wear, Uniforms',
  '7297': 'Massage Parlors',
  '7298': 'Health & Beauty Spas',
  '7299': 'Miscellaneous Personal Services',
  '7311': 'Advertising Services',
  '7321': 'Consumer Credit Reporting Agencies',
  '7332': 'Blueprinting & Photocopying Services',
  '7333': 'Commercial Photography, Art & Graphics',
  '7338': 'Quick Copy & Reproduction Services',
  '7339': 'Stenographic & Secretarial Support Services',
  '7342': 'Exterminating & Disinfecting Services',
  '7349': 'Cleaning, Maintenance & Janitorial Services',
  '7361': 'Employment & Temporary Help Agencies',
  '7372': 'Computer Programming & Data Processing',
  '7375': 'Information Retrieval Services',
  '7379': 'Computer Maintenance & Repair Services',
  '7392': 'Management, Consulting & Public Relations',
  '7393': 'Protective & Security Services',
  '7394': 'Equipment, Tool, Furniture & Appliance Rental',
  '7395': 'Photofinishing Laboratories',
  '7399': 'Business Services',
  '7511': 'Truck Stop',
  '7512': 'Automobile Rental Agencies',
  '7513': 'Truck & Utility Trailer Rentals',
  '7519': 'Motor Home & Recreational Vehicle Rentals',
  '7523': 'Parking Lots, Garages & Meters',
  '7531': 'Automotive Body Repair Shops',
  '7534': 'Tire Retreading & Repair Shops',
  '7535': 'Automotive Paint Shops',
  '7538': 'Automotive Service Shops',
  '7542': 'Car Washes',
  '7549': 'Towing Services',
  '7622': 'Radio Repair Shops',
  '7623': 'Air Conditioning & Refrigeration Repair Shops',
  '7629': 'Electrical & Small Appliance Repair',
  '7631': 'Watch, Clock & Jewelry Repair',
  '7641': 'Furniture Repair & Refinishing',
  '7692': 'Welding Repair',
  '7699': 'Miscellaneous Repair Shops',
  '7800': 'Government-Owned Lotteries',
  '7801': 'Government-Licensed Online Casinos',
  '7802': 'Government-Licensed Horse & Dog Racing',
  '7829': 'Film & Video Production & Distribution',
  '7832': 'Motion Picture Theaters',
  '7841': 'Video Tape Rental Stores',
  '7911': 'Dance Halls, Studios & Schools',
  '7922': 'Theatrical Producers & Ticket Agencies',
  '7929': 'Bands, Orchestras & Entertainers',
  '7932': 'Billiard & Pool Establishments',
  '7933': 'Bowling Alleys',
  '7941': 'Commercial Sports, Clubs & Promoters',
  '7991': 'Tourist Attractions & Exhibits',
  '7992': 'Public Golf Courses',
  '7993': 'Video Amusement Game Supplies',
  '7994': 'Video Game Arcades',
  '7995': 'Betting & Casino Gambling',
  '7996': 'Amusement Parks, Circuses & Carnivals',
  '7997': 'Membership Clubs & Private Golf Courses',
  '7998': 'Aquariums & Seaquariums',
  '7999': 'Recreation Services',
  '8011': 'Doctors & Physicians',
  '8021': 'Dentists & Orthodontists',
  '8031': 'Osteopaths',
  '8041': 'Chiropractors',
  '8042': 'Optometrists & Ophthalmologists',
  '8043': 'Opticians & Eyeglasses',
  '8044': 'Optical Goods & Eyeglasses',
  '8049': 'Podiatrists & Chiropodists',
  '8050': 'Nursing & Personal Care Facilities',
  '8062': 'Hospitals',
  '8071': 'Medical & Dental Laboratories',
  '8099': 'Medical Services & Health Practitioners',
  '8111': 'Legal Services & Attorneys',
  '8211': 'Elementary & Secondary Schools',
  '8220': 'Colleges & Universities',
  '8241': 'Correspondence Schools',
  '8244': 'Business & Secretarial Schools',
  '8249': 'Vocational & Trade Schools',
  '8299': 'Schools & Educational Services',
  '8351': 'Child Care Services',
  '8398': 'Charitable & Social Service Organizations',
  '8641': 'Civic, Social & Fraternal Associations',
  '8651': 'Political Organizations',
  '8661': 'Religious Organizations',
  '8675': 'Automobile Associations',
  '8699': 'Membership Organizations',
  '8734': 'Testing Laboratories (Non-Medical)',
  '8911': 'Architectural, Engineering & Surveying Services',
  '8931': 'Accounting, Auditing & Bookkeeping',
  '8999': 'Professional Services',
  '9211': 'Court Costs, including Alimony & Child Support',
  '9222': 'Fines',
  '9223': 'Bail & Bond Payments',
  '9311': 'Tax Payments',
  '9399': 'Government Services',
  '9402': 'Postal Services — Government Only',
  '9405': 'Intra-Government Purchases',
  '9700': 'Automated Referral Service',
  '9701': 'Visa Credential Service',
  '9702': 'GCAS Emergency Services',
  '9950': 'Intra-Company Purchases',
};

// "5451" -> "Dairy Products Stores"; '' when the code is absent or unlisted.
// "742" finds "0742", for a code stored without its leading zero.
export function mccName(mcc) {
  return MCC_NAMES[(mcc || '').trim().padStart(4, '0')] || '';
}
